-- MySQL Script generated by MySQL Workbench
-- Thu Jun 16 01:17:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rollcall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rollcall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rollcall` DEFAULT CHARACTER SET utf8 ;
USE `rollcall` ;

-- -----------------------------------------------------
-- Table `rollcall`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rollcall`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `usercol` VARCHAR(255) NULL,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `active` BINARY(1) NULL,
  `usercol1` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `registration_number` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rollcall`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rollcall`.`semester` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `created_on` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rollcall`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rollcall`.`attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `time_in` TIME NOT NULL,
  `time_out` TIME NOT NULL,
  `date` DATE NOT NULL,
  `semester_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendance_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_attendance_semester1_idx` (`semester_id` ASC) VISIBLE,
  CONSTRAINT `fk_attendance_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `rollcall`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_semester1`
    FOREIGN KEY (`semester_id`)
    REFERENCES `rollcall`.`semester` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rollcall`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rollcall`.`classes` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rollcall`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rollcall`.`units` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rollcall`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rollcall`.`courses` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `units_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courses_units1_idx` (`units_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_units1`
    FOREIGN KEY (`units_id`)
    REFERENCES `rollcall`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
